import type { Metadata } from 'next'
import '../style/main.css'
import { Header } from '../components'
import { UserProvider } from '@auth0/nextjs-auth0/client'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Header></Header>
          <main>{children}</main>
        </body>
      </UserProvider>
    </html>
  )
}
